#!/usr/bin/env python3
"""Regenerate modules/svg/shared/src/main/scala/intaglio/svg/UnicodeComposition.scala.

The table is every canonical primary composite: a code point whose canonical decomposition is
exactly two code points and which NFC recomposes from that pair (so composition exclusions and
singletons are absent). Hangul syllables and jamo are omitted: the SVG text-plate model treats
Hangul jamo as unmodelled shaping. The Unicode version is the running Python's unicodedata.
"""
import sys
import unicodedata
from pathlib import Path

out = (
    Path(__file__).resolve().parent.parent
    / "modules/svg/shared/src/main/scala/intaglio/svg/UnicodeComposition.scala"
)


def hangul(cp):
    return (
        0x1100 <= cp <= 0x11FF
        or 0xAC00 <= cp <= 0xD7A3
        or 0xA960 <= cp <= 0xA97F
        or 0xD7B0 <= cp <= 0xD7FF
    )


pairs = []
for cp in range(0x110000):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        continue
    parts = [int(x, 16) for x in d.split()]
    if len(parts) != 2 or hangul(cp) or hangul(parts[0]):
        continue
    if unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
        pairs.append((parts[0], parts[1], cp))

rows = []
line = ""
for a, b, c in pairs:
    entry = f"{a:x} {b:x} {c:x};"
    if len(line) + len(entry) > 84:
        rows.append(line)
        line = ""
    line += entry
rows.append(line)
body = " +\n".join(f'      "{r}"' for r in rows)
out.write_text(
    f"""package intaglio.svg

/** Canonical primary composites (Unicode {unicodedata.unidata_version}): `first second composite`, hexadecimal,
  * `;`-separated. Generated by `tools/generate-unicode-composition.py`; do not edit by hand. Hangul is
  * omitted because the SVG plate model does not model Hangul shaping.
  */
private[svg] object UnicodeComposition:
  val unicodeVersion: String = "{unicodedata.unidata_version}"

  private val table: String =
{body}

  private lazy val entries: Vector[(Int, Int, Int)] =
    table
      .split(';')
      .iterator
      .filter(_.nonEmpty)
      .map {{ entry =>
        val fields = entry.split(' ')
        (
          Integer.parseInt(fields(0), 16),
          Integer.parseInt(fields(1), 16),
          Integer.parseInt(fields(2), 16)
        )
      }}
      .toVector

  /** The composite of `first` followed by `second`, when Unicode defines a primary one. */
  lazy val compose: Map[(Int, Int), Int] =
    entries.iterator.map {{ case (first, second, composite) => (first, second) -> composite }}.toMap

  /** The canonical two-code-point decomposition of a primary composite. */
  lazy val decompose: Map[Int, (Int, Int)] =
    entries.iterator.map {{ case (first, second, composite) => composite -> (first, second) }}.toMap

  /** Code points that occur second in a composition pair: they combine with what precedes them. */
  lazy val combining: Set[Int] = entries.iterator.map(_._2).toSet
"""
)
print(f"{len(pairs)} pairs, Unicode {unicodedata.unidata_version}, {out}")
